# ===========================================================================
# CH13 -- implement the static design and every partial
# ===========================================================================
#   vivado -mode batch -source project_dfx_socket/build_impl.tcl
#
# Run after build_bd.tcl. Separate from it on purpose: the block design takes
# minutes and the implementation takes hours, and iterating on one should not
# mean redoing the other.
#
# What it does, in the order the DFX flow requires:
#
#   1. a pblock for the partition, clock-region aligned
#   2. one PR configuration per RM
#   3. the parent implementation -- static region plus the boot RM
#   4. one CHILD implementation per remaining RM, each with -parent_run the
#      parent. This is the step the spike got wrong: Vivado's auto-created
#      <bd>_inst_0_impl_1 runs are OUT-OF-CONTEXT runs, not DFX children, and
#      implementing a partial in one of those leaves the partition a black box.
#   5. pr_verify every configuration against the parent
#   6. bitstreams: one full, and one partial per RM

set script_dir [file dirname [file normalize [info script]]]
source [file join $script_dir .. common config.tcl]

set proj_dir  $script_dir/vivado
set proj_name dfx_socket
set out_dir   $script_dir/out
set bd_name   design_1
set boot_rm   passthrough
set jobs      12

open_project $proj_dir/$proj_name.xpr
file mkdir $out_dir

set socket_cell ${bd_name}_i/socket

# ---------------------------------------------------------------------------
# 1. The pblock, as a constraint rather than an interactive command
# ---------------------------------------------------------------------------
# create_pblock needs an OPEN design -- in project mode there is none at this
# point, and calling it here fails with
#   ERROR [Common 17-53] User Exception: No open design.
# So the pblock is written as XDC and applied during implementation, when the
# design is open and the cell exists.
#
# SNAPPING_MODE ON lets Vivado extend the region to legal reconfigurable frame
# boundaries. Without it a pblock that looks aligned is rejected at
# implementation with a DRC about frame alignment.
#
# RESET_AFTER_RECONFIG puts the new RM into a known state instead of whatever
# the fabric powered up as, and it is why the region is a WHOLE clock region:
# it requires clock-region alignment.
set pblock_xdc $script_dir/constraints/pblock.xdc
set fh [open $pblock_xdc w]
puts $fh "# GENERATED by build_impl.tcl -- edit ch13_pblock_region in common/config.tcl"
puts $fh "create_pblock pblock_socket"
puts $fh "add_cells_to_pblock \[get_pblocks pblock_socket\] \[get_cells $socket_cell\]"
puts $fh "resize_pblock \[get_pblocks pblock_socket\] -add {$ch13_pblock_region}"
puts $fh "set_property SNAPPING_MODE ON \[get_pblocks pblock_socket\]"
puts $fh "set_property RESET_AFTER_RECONFIG true \[get_pblocks pblock_socket\]"
puts $fh "set_property IS_SOFT false \[get_pblocks pblock_socket\]"
close $fh

if {[llength [get_files -quiet $pblock_xdc]] == 0} {
    add_files -fileset constrs_1 -norecurse $pblock_xdc
}
set_property used_in_synthesis false [get_files $pblock_xdc]
puts " pblock_socket -> $ch13_pblock_region (constraints/pblock.xdc)"

# ---------------------------------------------------------------------------
# 2. PR configurations, one per RM
# ---------------------------------------------------------------------------
set pd [get_partition_defs]
if {[llength $pd] != 1} { error "expected exactly one partition definition, got: $pd" }
puts " partition definition: [get_property NAME $pd]"

set configs {}
foreach name [ch13_rm_names] {
    set rm [get_reconfig_modules -quiet -of_objects $pd -filter "NAME =~ *${name}*"]
    if {[llength $rm] != 1} { error "expected one reconfig module for $name, got: $rm" }
    set rmname [get_property NAME $rm]
    set cfg config_$name
    if {![llength [get_pr_configurations -quiet $cfg]]} {
        create_pr_configuration -name $cfg -partitions [list $socket_cell:$rmname]
    }
    lappend configs $cfg
    puts "   $cfg -> $rmname"
}

# ---------------------------------------------------------------------------
# 3. The parent implementation: static region + the boot RM
# ---------------------------------------------------------------------------
set_property PR_CONFIGURATION config_$boot_rm [get_runs impl_1]

# ---------------------------------------------------------------------------
# 4. One child run per remaining RM
# ---------------------------------------------------------------------------
set child_runs {}
foreach name [ch13_rm_names] {
    if {$name eq $boot_rm} { continue }
    set r child_$name
    # Kept if it already exists, so re-running this script to resume does not
    # throw away a completed implementation.
    if {![llength [get_runs -quiet $r]]} {
        create_run $r -parent_run impl_1 -flow {Vivado Implementation 2025} \
            -pr_config config_$name
        puts " child run: $r (parent impl_1)"
    } else {
        puts " child run: $r exists ([get_property PROGRESS [get_runs $r]])"
    }
    lappend child_runs $r
}

# ---------------------------------------------------------------------------
# Synthesis, then the parent implementation, then the children
# ---------------------------------------------------------------------------
# Skip synthesis if it is already done -- this script is re-run while iterating
# on implementation, and re-launching a finished run is an error, not a no-op.
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    launch_runs synth_1 -jobs $jobs
    wait_on_run synth_1
}
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    error "synth_1 failed -- see $proj_dir/$proj_name.runs/synth_1"
}
puts " synth_1 complete"

# Every RM's own synthesis run. With a Block Design Container these are created
# for us, one per child design, and all of them must finish before any partial
# can be implemented.
#
# `launch_runs synth_1` already runs them: they are out-of-context runs of the
# container's child designs, and Vivado schedules them as dependencies. So the
# only ones to launch here are any that are somehow NOT complete -- launching a
# finished run is refused outright:
#   ERROR [Common 17-69] Runs '...' need to be reset before launching.
# which stops the build dead after a perfectly successful synthesis.
set rm_synth {}
foreach r [get_runs -quiet -filter {IS_SYNTHESIS && NAME =~ *inst_0_synth*}] {
    if {[get_property PROGRESS [get_runs $r]] ne "100%"} { lappend rm_synth $r }
}
if {[llength $rm_synth]} {
    puts " RM synthesis runs still to do: $rm_synth"
    launch_runs $rm_synth -jobs $jobs
    foreach r $rm_synth { wait_on_run $r }
}
foreach r [get_runs -quiet -filter {IS_SYNTHESIS && NAME =~ *inst_0_synth*}] {
    if {[get_property PROGRESS [get_runs $r]] ne "100%"} {
        error "$r did not complete ([get_property PROGRESS [get_runs $r]])"
    }
}
puts " all RM synthesis runs complete"

if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    launch_runs impl_1 -to_step write_bitstream -jobs $jobs
    wait_on_run impl_1
}
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    error "impl_1 failed -- see $proj_dir/$proj_name.runs/impl_1"
}

foreach r $child_runs {
    if {[get_property PROGRESS [get_runs $r]] ne "100%"} {
        launch_runs $r -to_step write_bitstream -jobs $jobs
        wait_on_run $r
    }
    if {[get_property PROGRESS [get_runs $r]] ne "100%"} {
        error "$r failed -- see $proj_dir/$proj_name.runs/$r"
    }
}

# ---------------------------------------------------------------------------
# 5. pr_verify -- the build gate
# ---------------------------------------------------------------------------
# Every configuration's STATIC region must be identical to the parent's, or the
# partials are not interchangeable. This is cheap and it is the only thing that
# actually proves it.
set parent_dcp $proj_dir/$proj_name.runs/impl_1/${bd_name}_wrapper_routed.dcp
set verify_fail 0
foreach r $child_runs {
    set child_dcp $proj_dir/$proj_name.runs/$r/${bd_name}_wrapper_routed.dcp
    if {![file exists $child_dcp]} { puts " pr_verify: $r has no routed dcp"; incr verify_fail; continue }
    # -initial/-additional, not a Tcl list as one positional argument. Passing
    # {dcp1 dcp2} is rejected with
    #   ERROR [Vivado 12-3499] Incorrect command format
    # even though the comparison itself has already run by then, which makes
    # the failure look like a verification failure rather than a typo.
    if {[catch {pr_verify -full_check -file $out_dir/pr_verify_$r.log \
                    -initial $parent_dcp -additional $child_dcp} msg]} {
        puts " pr_verify FAILED for $r: $msg"
        incr verify_fail
    } else {
        puts " pr_verify OK: impl_1 vs $r"
    }
}
if {$verify_fail} { error "pr_verify failed for $verify_fail configuration(s)" }

# ---------------------------------------------------------------------------
# 6. Collect the bitstreams
# ---------------------------------------------------------------------------
# Collect with names that say what each file IS.
#
# Every run writes a FULL bitstream as well as a partial, all called
# design_1_wrapper.bit, so copying them by their own names means four files
# overwriting each other and whichever ran last winning. The full bitstream
# that belongs in out/ is impl_1's -- the one whose socket holds the boot RM.
proc ch13_collect_partial {runs_dir out_dir name} {
    set hits [glob -nocomplain [file join $runs_dir *partial.bit]]
    if {[llength $hits] != 1} {
        error "expected one partial in $runs_dir, found: $hits"
    }
    set dst [file join $out_dir socket_${name}_partial.bit]
    file copy -force [lindex $hits 0] $dst
    return [file size $dst]
}

puts ""
puts "=== bitstreams ==="
set full_src $proj_dir/$proj_name.runs/impl_1/${bd_name}_wrapper.bit
if {![file exists $full_src]} { error "impl_1 produced no full bitstream" }
file copy -force $full_src $out_dir/dfx_socket.bit
puts [format "   %-34s %8.0f KB   full (static + %s)" \
        dfx_socket.bit [expr {[file size $full_src] / 1024.0}] $boot_rm]

# The boot RM's partial comes from impl_1; every other RM's from its child run.
set sz [ch13_collect_partial $proj_dir/$proj_name.runs/impl_1 $out_dir $boot_rm]
puts [format "   %-34s %8.0f KB   partial" socket_${boot_rm}_partial.bit [expr {$sz/1024.0}]]
foreach r $child_runs {
    set name [string range $r 6 end]
    set sz [ch13_collect_partial $proj_dir/$proj_name.runs/$r $out_dir $name]
    puts [format "   %-34s %8.0f KB   partial" socket_${name}_partial.bit [expr {$sz/1024.0}]]
}

# Every partial is the same size, and that is the point rather than a
# coincidence: a partial covers the whole PARTITION, so its size is set by how
# the socket was sized and not by what is in it. See docs/ch13-plan.md 6.1.

# The .hwh is what PYNQ reads to build the register maps.
set hwh [glob -nocomplain $proj_dir/$proj_name.gen/sources_1/bd/$bd_name/hw_handoff/$bd_name.hwh]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] $out_dir/dfx_socket.hwh
    puts " hwh: $out_dir/dfx_socket.hwh"
}

puts ""
puts "IMPL_DONE"
